export enum EventType {
  USER_AUTHENTICATED = 'USER_AUTHENTICATED',
  LOG_IN_FORM_SET_USERNAME = 'LOG_IN_FORM_SET_USERNAME',
  LOG_IN_FORM_SET_PASSWORD = 'LOG_IN_FORM_SET_PASSWORD',
  LOG_IN_ERROR = 'LOG_IN_ERROR',
  GUESS_ITEMS_FILTER_CATEGORY = 'GUESS_ITEMS_FILTER_CATEGORY',
  GUESS_ITEMS_SEARCH = 'GUESS_ITEMS_SEARCH',
  GUESS_ITEMS_LOADING = 'GUESS_ITEMS_LOADING',
  SET_GUESS_ITEMS_PAGE = 'SET_GUESS_ITEMS_PAGE',
  VIEW_GUESS_ITEM = 'VIEW_GUESS_ITEM',
  VIEW_GUESS_ITEM_DATA = 'VIEW_GUESS_ITEM_DATA',
  UPDATE_VIEW_GUESS_ITEM_TITLE = 'UPDATE_VIEW_GUESS_ITEM_TITLE',
  UPDATE_VIEW_GUESS_ITEM_CATEGORY = 'UPDATE_VIEW_GUESS_ITEM_CATEGORY',
  UPDATE_VIEW_GUESS_ITEM_STATUS = 'UPDATE_VIEW_GUESS_ITEM_STATUS',
  UPDATE_VIEW_GUESS_ITEM_ALT_NAMES = 'UPDATE_VIEW_GUESS_ITEM_ALT_NAMES',
  UPDATE_VIEW_GUESS_ITEM_HINT_TEXT = 'UPDATE_VIEW_GUESS_ITEM_HINT_TEXT',
  UPDATE_VIEW_GUESS_ITEM_HINT_LEVEL = 'UPDATE_VIEW_GUESS_ITEM_HINT_LEVEL',
  VIEW_GUESS_ITEM_ADD_HINT = 'VIEW_GUESS_ITEM_ADD_HINT',
  VIEW_GUESS_ITEM_REMOVE_HINT = 'VIEW_GUESS_ITEM_REMOVE_HINT',
  CLOSE_GUESS_ITEM_VIEW = 'CLOSE_GUESS_ITEM_VIEW',
}

export interface IEvent {
  type: EventType;
}
