export enum EventType {
  USER_AUTHENTICATED = 'USER_AUTHENTICATED',
  LOG_IN_FORM_SET_USERNAME = 'LOG_IN_FORM_SET_USERNAME',
  LOG_IN_FORM_SET_PASSWORD = 'LOG_IN_FORM_SET_PASSWORD',
  LOG_IN_ERROR = 'LOG_IN_ERROR',
  GUESS_ITEMS_FILTER_CATEGORY = 'GUESS_ITEMS_FILTER_CATEGORY',
  GUESS_ITEMS_SEARCH = 'GUESS_ITEMS_SEARCH',
  GUESS_ITEMS_LOADING = 'GUESS_ITEMS_LOADING',
  SET_GUESS_ITEMS_PAGE = 'SET_GUESS_ITEMS_PAGE',
}

export interface IEvent {
  type: EventType;
}
